VULTR Cloud Install Fixes
  - add vultr to cloud deployment checks
  - update cloud deployment checks
  - update `checkConn()` lib function
  - update same in `common` tests lib
  - fix external fqdn resolution for non-dns deployments
  - update `resetpassword()` cloud deployment check

diff --git a/testing/include/common b/testing/include/common
--- a/testing/include/common
+++ b/testing/include/common
@@ -131,70 +131,67 @@ setConfigAttrib() {
     sed -i -r -e "s|$NAME[ \t]*=[ \t]*.*|$NAME = $VALUE|g" ${CONFIG_FILE}
 }
 
-# returns: 0 == success, 1 == failure
+# returns: 0 == success, otherwise failure
 # notes: try to access the AWS metadata URL to determine if this is an AMI instance
-isInstanceAMI() {
-    curl -s -f --connect-timeout 2 http://169.254.169.254/latest/dynamic/instance-identity/ &>/dev/null; ret=$?
-    if (( $ret != 22 )) && (( $ret != 28 )); then
-        return 0
-    fi
-    return 1
+function isInstanceAMI() {
+    curl -s -f --connect-timeout 2 http://169.254.169.254/latest/dynamic/instance-identity/ &>/dev/null
+    return $?
 }
 
-# returns: 0 == success, 1 == failure
+# returns: 0 == success, otherwise failure
 # notes: try to access the DO metadata URL to determine if this is an Digital Ocean instance
-isInstanceDO() {
-    curl -s -f --connect-timeout 2 http://169.254.169.254/metadata/v1/ &>/dev/null; ret=$?
-    if (( $ret != 22 )) && (( $ret != 28 )); then
-        return 0
-    fi
-    return 1
+function isInstanceDO() {
+    curl -s -f --connect-timeout 2 http://169.254.169.254/metadata/v1/id &>/dev/null
+    return $?
 }
 
-# returns: 0 == success, 1 == failure
+# returns: 0 == success, otherwise failure
 # notes: try to access the GCE metadata URL to determine if this is an Google instance
-isInstanceGCE() {
-    curl -s -f --connect-timeout 2 -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/; ret=$?
-    if (( $ret != 22 )) && (( $ret != 28 )); then
-        return 0
-    fi
-    return 1
+function isInstanceGCE() {
+    curl -s -f --connect-timeout 2 -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/id &>/dev/null
+    return $?
 }
 
-# returns: 0 == success, 1 == failure
+# returns: 0 == success, otherwise failure
 # notes: try to access the MS Azure metadata URL to determine if this is an Azure instance
-isInstanceAZURE() {
-    curl -s -f --connect-timeout 2 -H "Metadata: true" "http://169.254.169.254/metadata/instance?api-version=2018-10-01"; ret=$?
-    if (( $ret != 6 )) &&(( $ret != 22 )) && (( $ret != 28 )); then
-        return 0
-    fi
-    return 1
+function isInstanceAZURE() {
+    curl -s -f --connect-timeout 2 -H "Metadata: true" "http://169.254.169.254/metadata/instance?api-version=2018-10-01" &>/dev/null
+    return $?
 }
 
-# TODO: support digital ocean and google cloud and microsoft azure
-# $1 == -aws | -do | -gce | -azure
-# returns: instance ID || blank string
+# returns: 0 == success, otherwise failure
+# notes: try to access the DO metadata URL to determine if this is an VULTR instance
+function isInstanceVULTR() {
+    curl -s -f --connect-timeout 2 http://169.254.169.254/v1/instanceid &>/dev/null
+    return $?
+}
+
+# output: instance ID || blank string
 # notes: we try checking for exported instance variable avoid querying again
-getInstanceID() {
+function getInstanceID() {
     if (( ${AWS_ENABLED:-0} == 1)); then
-        curl http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null ||
+        curl -s -f http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null ||
         ec2-metadata -i 2>/dev/null
     elif (( ${DO_ENABLED:-0} == 1 )); then
-        curl http://169.254.169.254/metadata/v1/id 2>/dev/null
+        curl -s -f http://169.254.169.254/metadata/v1/id 2>/dev/null
     elif (( ${GCE_ENABLED:-0} == 1 )); then
-        curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/id 2>/dev/null
+        curl -s -f -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/id 2>/dev/null
     elif (( ${AZURE_ENABLED:-0} == 1 )); then
-        curl -H "Metadata: true" "http://169.254.169.254/metadata/instance/compute/vmId?api-version=2018-10-01" 2>/dev/null
+        curl -s -f -H "Metadata: true" "http://169.254.169.254/metadata/instance/compute/vmId?api-version=2018-10-01" 2>/dev/null
+    elif (( ${VULTR_ENABLED:-0} == 1 )); then
+        curl -s -f http://169.254.169.254/v1/instanceid 2>/dev/null
     else
         if isInstanceAMI; then
-            curl http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null ||
+            curl -s -f http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null ||
             ec2-metadata -i 2>/dev/null
         elif isInstanceDO; then
-            curl http://169.254.169.254/metadata/v1/id 2>/dev/null
+            curl -s -f http://169.254.169.254/metadata/v1/id 2>/dev/null
         elif isInstanceGCE; then
-            curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/id 2>/dev/null
+            curl -s -f -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/id 2>/dev/null
         elif isInstanceAZURE; then
-            curl -H "Metadata: true" "http://169.254.169.254/metadata/instance/compute/vmId?api-version=2018-10-01" 2>/dev/null
+            curl -s -f -H "Metadata: true" "http://169.254.169.254/metadata/instance/compute/vmId?api-version=2018-10-01" 2>/dev/null
+        elif isInstanceVULTR; then
+            curl -s -f http://169.254.169.254/v1/instanceid 2>/dev/null
         fi
     fi
 }
