v0.621 Bug Fixes
  - fix missing parenthesis in kam cfg
  - add failure check to requirements creation in hook
  - rename async as identifier was shadowing builtin

diff --git a/resources/git/hooks/pre-commit b/resources/git/hooks/pre-commit
--- a/resources/git/hooks/pre-commit
+++ b/resources/git/hooks/pre-commit
@@ -82,6 +82,12 @@ createRequirements() {
         else
             LIBS=( ${INCLUDE_LIBS[@]} $(pipreqs --print ${EXCLUDE_ARGS} ${PYTHON_PROJECT} 2>/dev/null | sed -r '/^\s*$/d' | cut -d '=' -f 1) )
         fi
+
+        # make sure pipreqs didn't fail
+        if (( $? != 0 )); then
+            exit 1
+        fi
+
         printf '%s\n' "${LIBS[@]}" | sort -u > ${OUT_FILE}
 
         git add ${OUT_FILE}
